### ISSUE TITLE
Schnittstellenimplementierungen als Singleton gestalten

### ISSUE THREAD

**Issue by VRibeiro01** [KjellooMelloo/gameoftrons#114]

**Comment by KjellooMelloo** [comment]
Vermutlich auch für Caller-Objekte

**Comment by KjellooMelloo** [comment]
Wo wir schon dabei sind, Marshaler/ Unmarshaler dann auch Singleton

**Comment by VRibeiro01** [comment]
Wollen nicht übertreiben

**Comment by kathleen-neitzel** [comment]
- Nur Middleware als Singleton (unmarshaler und marshaler nicht)
- caller und callees aus appstub als singleton?
- factory, caller und callee für IControllerView?

**Comment by VRibeiro01** [comment]
Bei mir ist es done

**Comment by kathleen-neitzel** [comment]
@KjellooMelloo
