### ISSUE TITLE
View Anbindung zu Controller

### ISSUE THREAD

**Issue by VRibeiro01** [KjellooMelloo/gameoftrons#122]

**Comment by VRibeiro01** [comment]
Würde ich auch gern kurz mit dir durchgehen @kathleen-neitzel

**Comment by VRibeiro01** [comment]
Sollen wir mit Factory Pattern instanziieren oder nicht?
Hast du das Singleton-Pattern für deine IContext-Impl eingesetzt?
Ich habe meine View-Schnittstellenimplementierungen geändert:

Eine IViewImpl-Klasse mit allen Implementierungsmethoden (Klasse implementiert sowohl IControllerView als auch IModelView)

**Comment by VRibeiro01** [comment]
Die Sache mit der Tastaturbelegung ist bei mir vollständig implementiert (Fehlt nur noch in der Doku)

Das heißt aber dass ich dir nicht mehr unbedingt bei handleKeyboardInput die SpielerID mitschicken muss. 

Kannst du sagen ob wir uns darauf einigen, dass ich die Methode immer ohne die ID mitschicke?

**Comment by kathleen-neitzel** [comment]
- kein Factory Pattern für ControllerView
- Context ist Singleton: ja
- ich gucke mir deine ViewImpl an und passe bei mir falls nötig an
- ich schicke dir gleich pull request für meine View related Methoden
