### ISSUE TITLE
Für Model<-->Controller absprechen

### ISSUE THREAD

**Issue by kathleen-neitzel** [KjellooMelloo/gameoftrons#134]
andere Methode als cancelWait() zum löschen der Spielinstanz anbieten? Zugriff auf Spielerliste oder Spielinstanz gewähren oder bei cancelWait() alles löschen, dann setCurrentState("Delete") --> raus

benachrichtigungen für events, threads?

**Comment by kathleen-neitzel** [comment]
cancelWait() lokal oder remote --> wie wähle ich das aus? in State Waiting

**Comment by kathleen-neitzel** [comment]
model cancelWait() löscht selbst Spielinstanz? informiert alle Mitspieler oder nur lokal?, einmal absprechen wer zu Delete wechselt

**Comment by kathleen-neitzel** [comment]
wenn du setCurrentState("Game") setzt, sobald fullPlayerCount erreicht ist, brauche ich das nicht machen & du mich nicht benachrichtigen. also gerne entkommentieren

**Comment by KjellooMelloo** [comment]
> andere Methode als cancelWait() zum löschen der Spielinstanz anbieten? Zugriff auf Spielerliste oder Spielinstanz gewähren oder bei cancelWait() alles löschen, dann setCurrentState("Delete") --> raus

In cancelWait() wird einfach alles zurückgesetzt und dann setCurrentState("Delete") aufgerufen.

> benachrichtigungen für events, threads?

Im Model läuft zu dem Zeitpunkt noch nichts, außer der Timer, der cancelt wird. Bei dir läuft glaube ich nur ein Listener für Click auf Cancel(?), der könnte dann vielleicht in behavior() von DELETE zurückgesetzt werden oder?

**Comment by KjellooMelloo** [comment]
> cancelWait() lokal oder remote --> wie wähle ich das aus? in State Waiting

Wählst du nicht aus und weißt du auch nicht, das wird über die Factories geregelt. Habe das schon grob in #129 beschrieben, dass wir vermutlich sowas wie eine initialize() Methode in IModel, IModelView und IModelController brauchen, welche die Referenzen übergeben bekommen oder so. Die anderen Interface-Impls können sich dann einfach direkt die Referenz holen

**Comment by KjellooMelloo** [comment]
> model cancelWait() löscht selbst Spielinstanz? informiert alle Mitspieler oder nur lokal?, einmal absprechen wer zu Delete wechselt

Es gibt nicht wirklich eine "Spielinstanz", das GameManager-Objekt bleibt bestehen und setzt nur Werte zurück . Mitspieler werden, wenn remote, auch alle informiert

**Comment by KjellooMelloo** [comment]
> wenn du setCurrentState("Game") setzt, sobald fullPlayerCount erreicht ist, brauche ich das nicht machen & du mich nicht benachrichtigen. also gerne entkommentieren

Jap, ich hatte nur die ganzen Sachen kommentiert, weil es zu dem Zeitpunkt die Implementierungen noch nicht gab
