### ISSUE TITLE
Für View<-->Controller absprechen

### ISSUE THREAD

**Issue by kathleen-neitzel** [KjellooMelloo/gameoftrons#135]
EndScreen
Kommunikation von Events, Timer abgelaufen..

**Comment by kathleen-neitzel** [comment]
void handleInputPlayerCount(int playerCount)

**Comment by kathleen-neitzel** [comment]
kannst du mir im remote modus die player id als parameter mitsenden?
String handleDirectionKeyboardInput(int id, String key)

**Comment by kathleen-neitzel** [comment]
sind deine spieler ids von 0-5 oder von 1-6?

**Comment by kathleen-neitzel** [comment]
return für handleDirectionKeyboardInput rausnehmen, weil keine Callbacks zwischen Komponenten am besten & wir brauchen das auch nicht

**Comment by VRibeiro01** [comment]
1. return für handleDirectionKEyboardInput rausnehen finde ich gut und ist für mich gar kein Problem
2. Meine SpielerIDs sind von 0-5
3. Ich schicke dir immer die id bei handleKeyboardInput, dann kannst du das einfach anders handeln
