### ISSUE TITLE
Buffer-Größe im REceiver schlau festlegen

### ISSUE THREAD

**Issue by VRibeiro01** [KjellooMelloo/gameoftrons#144]
wie kann man das am besten machen, wenn es nicht bekannt ist, wie groß das empfangene Paket ist?

**Comment by KjellooMelloo** [comment]
Man könnte etwas hardcoden. Unser größtes UDP-Paket wäre bei updatePlayer und hat 164 byte. Das größte bei UDP ist register mit 111 bytes. Also einfach die nächste Zweierpotenz nehmen und dann sieht es professionell aus
