### ISSUE TITLE
Methodenauswahl remote/lokal

### ISSUE THREAD

**Issue by kathleen-neitzel** [KjellooMelloo/gameoftrons#179]
Soll der Controller die anderen Komponenten informieren, dass remote gespielt wird?
Kein Unterschied zwischen lokal/remote sollte bemerkbar sein --> Factory-Pattern!
Kommunikation über App Stub

**Comment by KjellooMelloo** [comment]
Kann glaube ich geschlossen werden, hatten wir gestern besprochen, Lösung in #181
