### ISSUE TITLE
Austausch Partnergruppe

### ISSUE THREAD

**Issue by kathleen-neitzel** [KjellooMelloo/gameoftrons#19]
Zweites Treffen organisieren
Methodenliste teilen (alle Methoden, die im NS registriert werden)
Übersetzungstabelle erstellen
Spielablauf schriftlich festhalten

**Comment by kathleen-neitzel** [comment]
Übersetzungstabelle @KjellooMelloo 
Gesamtablauf @kathleen-neitzel 
Partnergruppe: Doku @kathleen-neitzel

**Comment by KjellooMelloo** [comment]
War eher ein AUstausch
