### ISSUE TITLE
Bug: loadConfigParams --> parameter-Map leer

### ISSUE THREAD

**Issue by VRibeiro01** [KjellooMelloo/gameoftrons#248]
Parameter werden mit dem Regex nicht aus der Config geladen
Vermutlich, hat es mit dem Dateityp properties zu tun. Im Debugger hat die Variable "data" immer nur den Wert "gameoftrons.properties", also kann man damit nix anfangen.

Java bietet Methoden um properties zu laden. Das haben wir in der GameOfTrons (Klasse mit main) benutzt.

Code um Properties datei zu laden:

FileReader fr = new FileReader("gameoftrons.properties");
        Properties p = new Properties();
        p.load(fr);

Code, um eine bestimmte Property aus der Datei zu kriegen:
int port = (int) p.get("nameServerPort");

**Comment by kathleen-neitzel** [comment]
#251 #252 #
