### ISSUE TITLE
Bug offline Version des Spiels: Game Logic

### ISSUE THREAD

**Issue by VRibeiro01** [KjellooMelloo/gameoftrons#262]
Aufruf changePlayerDirection() --> getPlayerByID --> 2 Spieler, aber players hat die Länge 1 --> Index Out of Bounds Exception

**Comment by kathleen-neitzel** [comment]
Vermutete Ursache: join() sorgt auch im lokalen Modus dafür, dass nur 1 Spieler dem Spiel beitritt
idee: neue Methode setNumPlayers(int playerCount) für den remote modus
**initialisiert numPlayers Variable im Model auf entsprechende Spieleranzahl**
