### ISSUE TITLE
JavaFX Probleme mit Nebenläufigkeit

### ISSUE THREAD

**Issue by KjellooMelloo** [KjellooMelloo/gameoftrons#271]
Irgendwas GUI-related in der View muss auf dem Application Thread von JavaFX laufen, sonst klappt nichts. Gibt da scheinbar Möglichkeiten, bin aber auf keine Lösung gekommen

Links/ mögliche Lösungen:
- https://docs.oracle.com/javafx/2/threads/jfxpub-threads.htm
- https://stackoverflow.com/questions/29449297/java-lang-illegalstateexception-not-on-fx-application-thread-currentthread-t
- https://stackoverflow.com/questions/28627585/new-thread-application-still-running-after-stage-close/28629484#28629484
- https://www.demo2s.com/java/javafx-application-thread.html
- https://community.oracle.com/tech/developers/discussion/2503251/trying-to-update-ui-with-from-another-thread

**Comment by KjellooMelloo** [comment]
https://github.com/KjellooMelloo/gameoftrons/tree/remote-playing-bugfix
Da ist der letzte Stand mit ein paar vorherigen Fixes. nameserver ip auf eigene setzen nicht vergessen

**Comment by kathleen-neitzel** [comment]
Ursache: Host kommt in Lobby, TN hängt im Startbildschirm, notifyCountdownOver() kommt als Nachricht, aber Spiel wird nicht gestartet.
Fortschritt: View nutzt lokalen Controller für die Interface-Methoden, GameOfTrons registriert nicht mehr
- handleInputPlayerCount()
- handleWaitingButtonClick()
- handleDirectionKeyboardInput()
- notifyCountdownOver()

Aktuelles Problem: Host kommt in Spielbildschirm, letzter Teilnehmer hängt in der Lobby, Spiel wird gespielt
Fehler: View kann player für updatePlayer() nicht finden. Fehler vermutlich vorher in Lobby, setCurrentStateGame("GAME") nicht bei allen TN
