### ISSUE TITLE
Aktivitätsdiagramme Controller

### ISSUE THREAD

**Issue by kathleen-neitzel** [KjellooMelloo/gameoftrons#36]

**Comment by kathleen-neitzel** [comment]
START state machine
WAITING state machine
andere nochmal abchecken

**Comment by kathleen-neitzel** [comment]
Config-Methoden für Aktivitätsdiagramme uninteressant
- loadConfigParameters()
- loadDefaultPlayerCount()

**Comment by KjellooMelloo** [comment]
@kathleen-neitzel done oder?

**Comment by kathleen-neitzel** [comment]
yes @KjellooMelloo :)
