### ISSUE TITLE
Letzte Kapitel

### ISSUE THREAD

**Issue by kathleen-neitzel** [KjellooMelloo/gameoftrons#46]
Wer Ideen hat: gerne hinschreiben!

**Comment by KjellooMelloo** [comment]
Uns ist für Risiken vorhin nur eingefallen, dass unsere Fehlerbehandlung noch ausbaufähig ist und Ash hatte in der Doku nur sowas stehen wie "limitiert auf 2-6 Spieler" und "Nur eine Lobby, möglicherweise Bottleneck"

**Comment by KjellooMelloo** [comment]
In Architekturentscheidungen könnte man vielleicht die Anlehnung ans Buch erwähnen, dass man sich für  AppStub, MW, Client Stub mit Marshaler und Sender, Server Stub mit Unmarshaler und Receiver, etc. entschieden hat?

**Comment by KjellooMelloo** [comment]
In Architekturentscheidungen vermutlich auch Begründung für Entscheidung des Nameserver-Protokolls

**Comment by KjellooMelloo** [comment]
Risiko: Ein Model, single-point-of-failure. Spiel funktioniert für alle nicht mehr, wenn dieser Spieler abstürzt
