### ISSUE TITLE
Ausrichtung auf dem Board von Model zur View schicken

### ISSUE THREAD

**Issue by VRibeiro01** [KjellooMelloo/gameoftrons#87]
updatePlayer(int,int,int) --> updatePlayer(int,int,int,String) auf 
LS(Viviam)
Schnittstellenmethodenliste View(Viviam)
Whitebox-View(Viviam)

In #88 verschoben
|
v
Programmcode Model(Kjell)
Sequenzdiagramm (Kjell)

**Comment by KjellooMelloo** [comment]
Ich würde das aufteilen und einen neuen issue für meinen Teil machen, dass jeder auf einem branch arbeitet okay?
